### PR TITLE
Update example to use a thread pool for polling.

### PR DESCRIPTION
**Pull request by m4dc4p**
Updates the example to use a thread pool for getting notifications, so anyone copying the code doesn't give themselves a concurrency problem.

For issue #861.

### CODE REVIEW

**Comment by tpolecat** [comment]
I was thinking this would use `Timer.sleep`, lifted into `ConnectionIO`. Something like

```scala
Timer[IO].sleep(1.second).to[ConnectionIO]
```

This way there is no blocking.

**Comment by m4dc4p** [comment]
Thats a lot simpler. Does `Timer` use its own thread pool behind the scenes?

**Comment by tpolecat** [comment]
> Does `Timer` use its own thread pool behind the scenes?

No, it's nonblocking so it doesn't need to.

**Comment by m4dc4p** [comment]
Is `Timer...to[ConnectionIO]` a thing?

**Comment by tpolecat** [comment]
> Is `Timer...to[ConnectionIO]` a thing?

Yes, via `LiftIO`. You need `cats.effect.implicits._` for that syntax.

**Comment by m4dc4p** [comment]
I can't quite get this working.

**Comment by tpolecat** [comment]
Ok no worries, thanks for giving it a shot. I'll see if I can figure it out.

**Pull request closed without merging**
