### PR TITLE
trying to support metadata analysis of query output (without parameters)

### PR DESCRIPTION
**Pull request by refried**
Related to #228, no functional differences to @miketkelly's branch.  I'm currently building against this version.

### CODE REVIEW

**Comment by tpolecat** [comment]
I'm going to sit on this because I want to square this with the MS-SQL metadata issue first, but I think this is probably a good approach for now. Thanks!

**Comment by refried** [comment]
Anything I can do to help?  I can grab a SQL Server trial.

**Comment by tpolecat** [comment]
@refried thanks, I'll let you know. That might be helpful.

**Comment by tpolecat** [comment]
I tried a few things and I think this approach might be the best option. I was trying to make it emit a warning :warning: and continue if it can't figure out the parameter types, but there's no way to distinguish this case from a syntax error in the SQL, which should be a failure :x: ... they both show up as vendor-specific exceptions that I can't distinguish in a generic way.

With your approach you can just say ok I just won't look at the parameters. Which is lame but superior in that it works. So will probably merge unless I am inspired otherwise in the next few hours. :+1:

**Comment by refried** [comment]
I'm pretty happy with this for now, but to play devil's advocate: 
Does bad SQL let you get as far as `doobie.hi.preparedstatement#getParameterJdbcMeta`? And if not, how big of a mess would it make if you put a `catch` in there and changed the type to `PreparedStatementIO[Option[List[ParameterMeta]]]` or whatever you use for errors if not `Option`.

**Comment by tpolecat** [comment]
@refried Yeah I tried that. The problem is that `prepareStatement` doesn't do anything immediately (at least for PostgreSQL) so problems in the SQL don't appear until you ask for the metadata, at which point you can't distinguish bad SQL from failure fetching metadata. So you don't know if it should be a failure or a warning.

**Comment by tpolecat** [comment]
Closed via #235

**Pull request closed without merging**
