### PR TITLE
Fix docsite

### PR DESCRIPTION
**Pull request by calvellido**
This PR basically creates a menu for the book sidebar, and fix main page horizontal menu positions.

If you feel like styles are misbehaving on some pages, check that you executing locally something like this (form the project root)

`jekyll serve -s ./modules/docs/target/site -b /doobie`

### CODE REVIEW

**Comment by tpolecat** [comment]
Man I appreciate this so much, thank you!

**Comment by tpolecat** [comment]
Hm do you have any idea why Introduction comes last in the TOC instead of first?

image

**Comment by calvellido** [comment]
Weird, can't think on anything that could cause that :thinking: 

I disabled all `mdoc` to generate this, but shouldn't change the outcome:

image

Do you have any more local changes beyond what it's in this branch?

**Comment by calvellido** [comment]
@tpolecat try this though: https://github.com/tpolecat/doobie/pull/1169

**Pull request merged**
