### PR TITLE
Fix Travis builds for the new ubuntu trusty default environment

### PR DESCRIPTION
**Pull request by Jacoby6000**
Looks like the `precise` environment had the `postgresql-9.3-postgis-2.3` apt package installed by default, and `trusty` does not.  This was causing a failure whenever the before-script tried to create the postgis extension.  I added the package to `addons.apt.packages` in `.travis.yml`.  This [seems to have fixed the problem](https://travis-ci.org/Jacoby6000/doobie/jobs/257047857). Another solution would be to set the `dist` to `precise` in the build file, but if the default env is going to be `trusty` I figure it's best just to roll with it.

### CODE REVIEW

**Comment by tpolecat** [comment]
Brilliant, thanks! We'll see what Travis says.

**Comment by Jacoby6000** [comment]
Well, that is certainly an interesting failure mode.

**Comment by tpolecat** [comment]
fascinating

**Comment by Jacoby6000** [comment]
Ah, it's failing while building the docs.  The failures also seem to be valid failures.  I wonder why these didn't show up before.

**Comment by tpolecat** [comment]
Closed via #557

**Pull request closed without merging**
