### PR TITLE
Add EXPLAIN and EXPLAIN ANALYZE output to Query.

### PR DESCRIPTION
**Pull request by m4dc4p**

### CODE REVIEW

**Comment by m4dc4p** [comment]
"[error] java.lang.RuntimeException: doobie-core: Binary compatibility check failed!"

Do I need to bump a version number somewhere?

**Comment by m4dc4p** [comment]
Wrong branch.

**Comment by tpolecat** [comment]
Hi, thanks for this. Unfortunately `EXPLAIN` is vendor-specific so we can't really add it to `Query/Query0` directly, but you could get there via a generic method that lets you inspect the SQL and the program that sets the statement parameters. Something like this maybe? (off the top of my head, may not even typecheck)

```scala

// on Query
def inspect[B](a: A)(f: (String, PreparedStatementIO[Unit]) => ConnectionIO[B]): ConnectionIO[B] =
  f(sql, HPS.set(a))

// Somewhere in the postgres module
implicit class PostgresQueryOps[A](self: Query[A]) {

  def explain(a: A): ConnectionIO[List[String]] =
    self.inspect { (sql, prepare) =>
      HC.prepareStatement(s"EXPLAIN $sql")(prepare *> HPS.executeQuery(a, HRS.build[List, String]))
    }

}
```

**Comment by m4dc4p** [comment]
Thanks for the guidance! I added `explainAnalyze` and `explain` to `Query0` and `Query` when `postgres.implicits._` is in scope.

I added some info to the documentation, but all I was able to do was run `docs/tut` - I'm not sure if the HTML generated looks good or not ...

Please check out the updated implementation.

**Comment by tpolecat** [comment]
Can you rebase this onto 0.8.x?

**Comment by m4dc4p** [comment]
> 
> 
> Can you rebase this onto 0.8.x?

Done! See #942 (branch names got too confusing here.)

**Pull request closed without merging**
