### PR TITLE
remove quill integration

### PR DESCRIPTION
**Pull request by tpolecat**
This removes integration with Quill, which is now part of the ZIO organization, which I will not support.

### CODE REVIEW

**Comment by deusaquilus** [comment]
Is there something that is good and right to say here? I don't know.

I'm really, really sorry that it's come to this. @tpolecat, you're a great author of a wonderful library. Together we made something fun and useful that makes many people's lives easier and more fun. If there was something I knew I could say to somehow reconcile the vast chasm that has opened up between our communities then I would say it right now. If there was something I knew I could say to heal anything and anyone then I would say it right now. I can't undo or un-say anything has has been done or said by others over these past four years and I can't change anyone's opinion about anything at all in these short keystrokes.

Will the whole Scala world be opened up and ripped apart by this conflict? Will every library and every repo have to eventually pick a side to love and a side to spurn? I hope not. I hope that our ideals are not forever irreconcilable and that this conflict will not be the span of decades.

This is sad. Really, really sad.
I don't know what else to say.

**Comment by chrilves** [comment]
I'm just a user but I want you @tpolecat to know that some users understand this decisions.

**Comment by ccellado** [comment]
Hell is full of good meanings, but heaven is full of good works.

**Comment by kubukoz** [comment]
I've set up a copy of this in https://github.com/polyvariant/doobie-quill, there's a snapshot on s01.oss.sonatype.org and a numbered release on syncing to Maven Central.

@tpolecat just to have paper trail, license-wise is this okay for you?

**Comment by Guisanpea** [comment]
I firmly believe that we should respect library authors deciding not to maintain a project any longer, regardless of the impact it may have on the community.

Open source contributors are regular people who choose to spend their spare time creating something good for the rest of us. The time they are contributing to their projects is time they are not dedicating to their personal life.

Even if you don't care about library authors, if they work on something they are not comfortable with, they are less likely to make it great.

And I think that it is not a big deal if doobie-quill stops being developed by @tpolecat. It can still be developed by other people who really feel like doing it. That's the good thing about functional programming, we can compose things. Doobie is a lego piece and Quill is another lego piece, if the maintainer of one of those is not a maintainer of the combination it is not that big of a deal.

If we want a healthy open source community let maintainers be free and make their decisions without consequences

**Comment by tpolecat** [comment]
@kubukoz yes, the fork without attribution is fine. Thanks for asking.

**Comment by odersky** [comment]
I think this disqualifies both doobie and TypeLevel from further conversation. You can do what you want. But I am sick of this kind of politics.

**Comment by nafg** [comment]
> Will the whole Scala world be opened up and ripped apart by this conflict? Will every library and every repo have to eventually pick a side to love and a side to spurn? I hope not.

So do I. But this childish move is itself a step in this direction. @tpolecat don't you realize how much this harms the entire Scala community and adoption? Someone will probably post this on Reddit and the entire world's existing belief that people in the Scala community are toxic will be reinforced. Please don't do this to us. You're killing Scala adoption when you do things like this.

**Comment by kubukoz** [comment]
@odersky so this is enough to punish the entirety of Typelevel, but when ZIO maintainers post FUD about TL libraries that's fine?

@nafg that's an interesting way to say "you're a hostage of this code now, keep publishing it or you'll be blamed for the community's downfall"

**Comment by tpolecat** [comment]
Alright that's about enough. Thanks everyone for your input.

**Pull request merged**
