### PR TITLE
Composable fragments helpers

### PR DESCRIPTION
**Pull request by sideeffffect**
Make `and`/`or` & co. composable and add `comma` and `orderBy` `fragments` helpers

closes https://github.com/tpolecat/doobie/pull/903

### CODE REVIEW

**Comment by tpolecat** [comment]
I assume this subsumes the old PR.

**Comment by sideeffffect** [comment]
Long time has passed, but I feel like the proposed changes still bring value to doobie users (myself included). Rob, what do you think about this change or a change similar in spirit making its way into doobie?

**Comment by sideeffffect** [comment]
@jatcwang how do you feel about this one?

**Comment by jatcwang** [comment]
@sideeffffect yes please reopen :)

I'm not too sure about the breaking changes though. Doobie users will be upgrading to 1.x along with CE3 so I want to avoid compile errors unless necessary. Though I am unable to come up with good alternative names atm

**Pull request closed without merging**
