### PR TITLE
Update to 2.12.0-M4/5 and get build to be reliable, merge minor PRs

### PR DESCRIPTION
**Pull request by tpolecat**
Travis is crapping out on series/0.3.x which is preventing merging of a couple PRs. Trying to get it working here. resolves #301 #306 #307 

Many Updates:
- Scala 2.12.0-M4
- ScalaCheck 1.13.1
- Specs2 3.8.4
- Kind-Projector 0.8.0
- Scalaz 7.2.4
- Scalaz-Stream 0.8.2a
- Shapeless 2.3.1
- tut 0.4.3

### CODE REVIEW

**Comment by tpolecat** [comment]
Removed 2.12 from the build because artifacts for M3 don't exist for scalaz, and artifacts for M4 don't exist for scalaz-stream.

**Comment by xuwei-k** [comment]
Scala 2.12.0-M5 ?

**Comment by tpolecat** [comment]
Oh thanks Kenji, I didn't know there was an M5. I'll give it a try.

**Comment by xuwei-k** [comment]
- http://repo1.maven.org/maven2/org/scalaz/stream/scalaz-stream_2.12.0-M5/
- http://repo1.maven.org/maven2/org/scalaz/scalaz-core_2.12.0-M5/
- http://repo1.maven.org/maven2/com/chuusai/shapeless_2.12.0-M5/
- http://repo1.maven.org/maven2/org/scalacheck/scalacheck_2.12.0-M5/

**Comment by tpolecat** [comment]
@xuwei-k thanks, now I need to publish tut for M4 and M5…

**Pull request merged**
