### PR TITLE
2.13.0 Support

### PR DESCRIPTION
**Pull request by ChristopherDavenport**
2.13.0-M5 Support In Place

Currently having an issue with the PostGIS build

### CODE REVIEW

**Comment by tpolecat** [comment]
Wow. I'll have a look in the morning, thanks!

**Comment by tpolecat** [comment]
Wow I don't understand that Travis build at all, but it looks great! Are there any issues as far as you know?

**Comment by ChristopherDavenport** [comment]
Your biggest gotcha would be if you run `sbt ++2.13.0-M5 test` or similar rather than `sbt ++2.13.0-M5 thirteen/test` you will run into issues with docs and quill and the missing dependencies you saw when you were fighting it earlier. But we move around it entirely with the project, and let the crossVersioning on each of the sub-projects control the release process with there being no cross-versions for any of the top level projects. 

So in general I think this is good to go. But it will be very nice to remove when all your dependencies have releases.

**Comment by ChristopherDavenport** [comment]
Also I had to force trusty, because the postGIS issue was due to something changing with the Xenial gis process. So that means when you change that base image there will be some changes needed to your before_travis script.

**Comment by tpolecat** [comment]
Sounds great, thanks.

**Pull request merged**
