### PR TITLE
Cats 0.9.0

### PR DESCRIPTION
**Pull request by adelbertc**

### CODE REVIEW

**Comment by tpolecat** [comment]
No circe for cats 0.9 yet so book chapter 12 is barfing. When it's released need to update `build.sbt:389`.

**Comment by tpolecat** [comment]
Also thanks!

**Comment by guersam** [comment]
[circe 0.7.0](https://github.com/circe/circe/releases/tag/v0.7.0) depends on cats 0.9 :+1:

**Comment by tpolecat** [comment]
@adelbertc sorry, I pushed a doc change so you're out of date. Can you rebase?

**Pull request merged**
