### PR TITLE
Fix logging for streaming and updateMany

### LINKED ISSUE #533: withGeneratedKeys & transaction statements missing from logs
On 0.4.2-SNAPSHOT inserts using `withUniqueGeneratedKeys` aren't being logged:
```scala
sql"INSERT INTO...".update.run
```
works, but this doesn't:
```scala
sql"INSERT INTO...".update.withUniqueGeneratedKeys[Long]("id")
```
I'm using an implicit `LogHandler`

Also, is there any way of logging the BEGIN/COMMIT/ROLLBACK statements? I think it's useful info, makes it easier to parse visually when examining multiple transactions. 
You have no way of knowing which statements have been rolled back otherwise, nor can you see the time it takes to perform a ROLLBACK/COMMIT like you can with other statements.

### PR DESCRIPTION
**Pull request by jatcwang**
Introduces three new functions in the high level API for Connection (`doobie.hi.HC`).

Fixes #533, #1888

These helpers offer a few improvements:

- Logging support
- Handle and log exceptions throw during the PreparedStatement creation (Some JDBC drivers do this if the table doesn't exist)
- A slighly simpler "flat" API for anyone that wants to customize their query

## `executeWithResultSet`
This is a generalization for any query that executes a PreparedStatement and processes a ResultSet. This covers two cases:

- A normal select query (JDBC's `executeQuery`)
- An update which generates returned rows (i.e. `RETURNING` / `.executeUpdate + .getGeneratedKeys`)

All query methods like Query#to and Update#withUniqueGeneratedKeys have switched to use this internally.

##  `executeWithoutResultSet`

Similar to `executeWithResultSet` but for queries that doesn't need to process a ResultSet (i.e. simple updates).

Methods like `Update`'s `updateMany`, `update` have switched to use this internally

## `stream`
This will be replacing the existing `stream` method (which is currently deprecated because it doesn't support logging)

`Query#stream` and all the `Update#withGeneratedKeys*` have switched to this internally.

Further improvements can probably be made on top of these methods so users don't need to construct `LoggingInfo` themselves.

### CODE REVIEW

**Comment by henricook** [comment]
Thanks for this improvement @jatcwang . I'm trying to convert some existing code when migrating from RC6 -> RC7 due to the deprecation and wonder if you have a minute to provide some guidance? 🙏🏻 

Old code:

```scala
HC.prepareStatement(sql)(HPS.executeQuery {
      for {
        md <- FRS.getMetaData
        rs <- row(md).whileM[List](HRS.next)
      } yield RawResultSet(header(md), rs)
    })
```

It's unclear to me how to convert this to the FC.prepareStatement / executeWithResultSet style, i've got something like this so far:

```scala
  private def exec(sql: String): ConnectionIO[RawResultSet] = {

    val preparedStatement = FC.prepareStatement(sql)

    doobie.hi.connection.executeWithResultSet(
      create = preparedStatement,
      prep = ???,
      exec = ???,
      process = ???,
      LoggingInfo(sql, NonBatch(List.empty), "fooLabel")
    )
```

It's unclear to me how to/what to put in prep, exec and process - might you have any pointers? Or a method I'm missing which just takes care of it for me?

My use case here is running (admin) user provided SQL without any bound parameters - just a straight string -> query mapping.

**Comment by jatcwang** [comment]
Hi @henricook sorry the documentation for custom JDBC operations isn't really there and I haven't gotten around to #2134 yet.

In your case,
- prep: You don't need a prepare step, so you can use `FPS.unit`
- exec: `FPS.executeQuery`
- process: 
```
for {
  md <- FRS.getMetaData
  rs <- row(md).whileM[List](HRS.next)
} yield RawResultSet(header(md), rs)
```

Hope that works!

**Comment by henricook** [comment]
Thanks for a super speedy response @jatcwang. I was reading the MR but Doobie novice that I am it took me a while to realise that IFPS FPS etc are all remappings of things like `doobie.free.preparedstatement`.

Here's my compiling and working final item based on your comments, currently without the 'doobie idiomatic' remapping of `doobie.free.preparedstatement' to `FPS` and `doobie.hi.connection` to `IHC`  - i'll do that next

Notes: 
  - I have no params to bind, so this isn't suitable if you're reading and hoping to bind parameters. 
  - `mkLabel` is a custom method I use just to prefix a repository name onto the label

```scala
private def exec(sql: String): ConnectionIO[RawResultSet] = {

    val preparedStatement = FC.prepareStatement(sql)

    doobie.hi.connection.executeWithResultSet(
      create = preparedStatement,
      prep = doobie.free.preparedstatement.unit,
      exec = doobie.free.preparedstatement.executeQuery,
      process = (for {
        md <- FRS.getMetaData
        rs <- row(md).whileM[List](HRS.next)
      } yield RawResultSet(header(md), rs)),
      LoggingInfo(sql, NonBatch(List.empty), mkLabel("executeQuery"))
    )
```

**Comment by jatcwang** [comment]
Thanks for posting an update @henricook glad it worked :partying_face:

**Comment by strokyl** [comment]
Thanks @henricook for the shared code, it was really useful to me today

**Pull request merged**
