### PR TITLE
wip: add scalatest module

### LINKED ISSUE #350: scalatest support
wip on #331

### PR DESCRIPTION
**Pull request by KadekM**
This is just the most naive port of Specs2 stuff to Scalatest 

and option to ignore checking of some columns, because in our codebase we use postgres enums and they check fails for them even when query is valid. There is hacky way I extract column name using regex, so if someone could check it out ... I can also remove this functionality if it's desired to match specs2 stuff 1:1.

Lets see if it builds ...

resolves #350

### CODE REVIEW

**Comment by KadekM** [comment]
I guess I should not have updated that readme... since it's only on snapshot and it's going to be without contrib part anyways...

**Comment by tpolecat** [comment]
I don't have time to look at this right now but I'll try to get to it by the end of the week. Thanks!!

**Comment by KadekM** [comment]
@tpolecat is there intention to get his merged? Anything I should do/change ? : )

**Comment by tpolecat** [comment]
Sorry, thanks for the ping. Yes, I want to get this in for 0.3.1 … I will add an issue to be sure it's tracked. You will need to rebase but wait until I have a chance to review it.

**Comment by KadekM** [comment]
the code to ignore column is only due to #303 , I'm happy to remove it once we have it fixed or replace with something more sensible than regex :-)

**Pull request closed without merging**
