### PR TITLE
Fix analysis when using h2 + UUIDs

### PR DESCRIPTION
**Pull request by Jacoby6000**
Fixes a portion of #552. I haven't been able to figure out what's up with merge statements reporting VARCHAR for every type.. I was able to kind of fix it by using the composite to set the params before running the analysis, but things still acted funky in situations involving NULL.

### CODE REVIEW

**Comment by tpolecat** [comment]
Looks good. 👍 Can you add a bullet point to `CHANGELOG.md`?

**Comment by Jacoby6000** [comment]
👍 done.

**Comment by tpolecat** [comment]
Thanks!

**Comment by Jacoby6000** [comment]
@tpolecat the travis errors that are happening are probably because the default linux dist in Travis changed from `precise` to `trusty` recently.  Your most recent successful build was on `precise` and all failing builds are on `trusty`.

**Comment by tpolecat** [comment]
Hell.

**Pull request merged**
