### PR TITLE
remove jdk9+ stuff

### PR DESCRIPTION
**Pull request by tpolecat**
Somehow [this commit](https://github.com/tpolecat/doobie/commit/3231e7928e7eee5a4a91b32d7bdc2836381d1f0e) got dropped and we ended up with JDK9+ JDBC stuff in here. This removes it and pushes the CI version back to 8.

### CODE REVIEW

**Comment by tpolecat** [comment]
ffs

**Comment by tpolecat** [comment]
now tests are failing, what on earth

**Comment by jatcwang** [comment]
This may help https://stackoverflow.com/questions/61490701/offsetdatetime-parse-different-behavior-in-java-8-and-java-11

Seems like OffsetDateTime parsing become more lenient in JDK 9+ (optional minutes)

**Comment by tpolecat** [comment]
It turns out I was installing JDK8 but the build was actually running in JDK11 all this time, per @armanbilge. Computers are the worst.

**Comment by SethTisue** [comment]
scala/community-build@e8d41c1683142a559fc054ad624f1f258aeb80b1

**Pull request merged**
