### PR TITLE
update scalaz-stream 0.8.4a

### PR DESCRIPTION
**Pull request by coltfred**

### CODE REVIEW

**Comment by tpolecat** [comment]
Looks like you also need to update to 2.12.0-M5 in `.travis.yml` and `build.sbt`. Other deps may not be out for M5 yet so if that fails we may need to wait.

**Comment by tpolecat** [comment]
Also thanks!

**Comment by coltfred** [comment]
```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.spire-math#kind-projector_2.12.0-M5;0.8.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
``` 
:panda_face:  Maybe @non will grace me with a published version of Kind Projector?

**Comment by tpolecat** [comment]
blergh

**Comment by coltfred** [comment]
@non I've opened a PR against kind projector. https://github.com/non/kind-projector/pull/29

**Comment by tpolecat** [comment]
@coltfred do you want to give this another go with 0.9? I think KP is up to date now.

**Comment by tpolecat** [comment]
Actually I don't know if there's anything you need to do. Restarted the build.

**Comment by tpolecat** [comment]
Welp. KP is at 0.9 now but it's on 2.12.0-RC1 which doesn't have a shapeless release due to a regression. May just need to hold off until 2.12.0 ships. This dance is maddening.

**Comment by coltfred** [comment]
Ultimately, this is the problem with cross building for scala versions which aren't really stable yet. Personally I'd just ship the update for 2.10.x and 2.11.x and stop messing with 2.12 until they get their poop in a group, but if you'd rather wait I'm fine with it.

**Comment by non** [comment]
@tpolecat Sorry! I was worried about M5 versus RC1 but opted for the more recent one. :/

**Comment by tpolecat** [comment]
@non no worries, it's going to be a hassle until 2.12.0 is out. I'm not worried about it.

**Comment by gatorcse** [comment]
@tpolecat Looks like scalaz-stream dependency is already past this, can probably close this branch.

**Pull request closed without merging**
