### PR TITLE
Updated for shapeless-2.2.0. Removed boilerplate.

### LINKED ISSUE #88: Upgrade to shapeless 2.2.0

### PR DESCRIPTION
**Pull request by milessabin**
I'll update this PR once shapeless-2.2.0-RC2 is published ... feel free to kick the tyres in the interim.

**RCN**: this fixes #88

### CODE REVIEW

**Comment by tpolecat** [comment]
Tried it out locally, works! Great stuff. Looking forward to the release (no hurry).

**Comment by milessabin** [comment]
Is this failing now while tut is trying to build the docs for 2.10.x?

**Comment by tpolecat** [comment]
Hell. Yeah the `docs` project needs paradise as well. Might be best to just add it to `ThisBulid` in the top-level `build.sbt` if that's possible since anyone might need it.

**Comment by tpolecat** [comment]
Subsumed by #159 ... all working modulo sbt bullshit. Thanks!

**Pull request closed without merging**
