### PR TITLE
Add facilities for transacting Kleisli and stream of Kleisli

### PR DESCRIPTION
**Pull request by bplommer**
Happy to add tests if desired 🙂

### CODE REVIEW

**Comment by bplommer** [comment]
I don't think the CI failure is related to this PR.

**Comment by tpolecat** [comment]
Yep, restarted that build. Thanks for your contribution, I'll try to have a look soon!

**Comment by bplommer** [comment]
Oops, seems I forgot to push some changes that were needed to get scalac to find the Kleisli Stream syntax. I'll push them in a few hours when I get home from work.

**Comment by tpolecat** [comment]
Thanks!

**Pull request merged**
