### PR TITLE
Replace logHandler with label in Query and Update

### PR DESCRIPTION
**Pull request by george-wilson-rea**
I really want `RC3` to be released, so I've had a go at #1821 . What do you think?

* I've used "unlabaled" in a case where the user does't provide a label. Do you like that, or would you like empty string or something else? Maybe `Option[String]`?
* I've added the label, but I don't understand what to do with it in the transactor.

### CODE REVIEW

**Review by jatcwang — APPROVED** [review]
Thanks @george-wilson-rea that's exactly what I have in mind :)
I don't think we're actually logging it atm right? That can be added in a follow up PR if you want to take a stab at it, or leave it and I'll get to it 👍

**Comment by george-wilson-rea** [comment]
@jatcwang I'm not logging it anywhere. I don't really understand where to log it. The issue says somewhere in the `Transactor` but where? Admittedly I don't really understand how doobie is implemented; I just followed the types to make this change.

If you could tell me where and how to do the logging, I'm happy to do it as part of this pull request. I also want to move `"unlabeled"` out to a constant somewhere, rather than duplicating the string literal in several places.

It looks like the build failed; should I be worried about that?

Also I notice that a bunch of the scala steward PRs are still open after quite some time. Can you merge them?

**Comment by george-wilson-rea** [comment]
Looks like the build breakage is docs-related. I'll see what I can do...

**Comment by jatcwang** [comment]
Thanks! If you want to take a stab at it, you can modify `doobie.util.log.LogEvent` to include `label` and follow the type errors.
(You should eventually modify e.g. `doobie.util.query.Query#executeQuery`)
I recommend adding it behind the  `args` parameter :)

**Comment by george-wilson-rea** [comment]
Ok, I've tried logging the label. See what you think. I still need to fix the docs.

**Comment by george-wilson-rea** [comment]
Hopefully the tests will pass now. I don't know what to update the docs with because I don't understand where the LogHandler gets set now.

**Comment by jatcwang** [comment]
I'll push some commits to update the docs. Thanks for your PR!

**Comment by hamnis** [comment]
maybe the label should be a newtype surrounding string, as having raw strings as implicit parameters feels bad.

**Comment by jatcwang** [comment]
@hamnis I agree but the label doesn't seem to be an implicit parameter atm?

**Comment by hamnis** [comment]
@jatcwang it is an implicit here: https://github.com/tpolecat/doobie/pull/1849/files#diff-97913cd15deed5b279aee8307f32609d81658d2af5abfccbd53005e58b960bb4R206

that seems to be the only instance though

**Comment by jatcwang** [comment]
@hamnis Good catch thank you. Fixed :)

**Pull request merged**
