### PR TITLE
cross-build/publish for Scala 2.10.x

### PR DESCRIPTION
**Pull request by jeffreyolchovy**
@tpolecat you almost had it...

Easier to see the integral changes that needed to be made if you look at the individual diffs of https://github.com/tpolecat/doobie/pull/564/commits/6a6a1895f7f742f075f9f87551e24bdf6dd57b00 and https://github.com/tpolecat/doobie/pull/564/commits/419c5d07e4b110e8f6e385ed5c06e36d77a31637.

The last commit was what I used for locally testing the release process, so you'll want to remove that prior to merge/release.

When performing a release, you just issue `release` from the `doobie` (root/aggregate project). **Nothing more, nothing less**.

```
$ sbt
[info] Loading project definition from /doobie/project/project
[info] Loading project definition from /doobie/project
[info] Updating doobie-build
[info] Resolved doobie-build dependencies
[info] Fetching artifacts of doobie-build
[info] Fetched artifacts of doobie-build
[info] Resolving key references (10776 settings) ...
[info] Set current project to doobie (in build file:/doobie/)
> release
... # cross-release process begins
```

The results of the my release process (the locally published artifacts) were:
```
$ ls -l .ivy2/local/org.tpolecat/
total 0
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:14 doobie-core-cats_2.11
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:16 doobie-core-cats_2.12
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:12 doobie-core_2.10
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:14 doobie-core_2.11
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:16 doobie-core_2.12
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:14 doobie-h2-cats_2.11
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:16 doobie-h2-cats_2.12
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:12 doobie-h2_2.10
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:14 doobie-h2_2.11
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:16 doobie-h2_2.12
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:14 doobie-hikari-cats_2.11
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:16 doobie-hikari-cats_2.12
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:12 doobie-hikari_2.10
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:14 doobie-hikari_2.11
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:16 doobie-hikari_2.12
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:14 doobie-postgres-cats_2.11
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:16 doobie-postgres-cats_2.12
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:12 doobie-postgres_2.10
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:14 doobie-postgres_2.11
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:16 doobie-postgres_2.12
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:14 doobie-refined-cats_2.11
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:16 doobie-refined-cats_2.12
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:12 doobie-refined_2.10
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:14 doobie-refined_2.11
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:16 doobie-refined_2.12
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:14 doobie-scalatest-cats_2.11
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:16 doobie-scalatest-cats_2.12
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:12 doobie-scalatest_2.10
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:14 doobie-scalatest_2.11
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:16 doobie-scalatest_2.12
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:14 doobie-specs2-cats_2.11
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:16 doobie-specs2-cats_2.12
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:12 doobie-specs2_2.10
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:14 doobie-specs2_2.11
drwxr-xr-x+ 3 jeffo  staff  102 Aug  4 10:16 doobie-specs2_2.12
```

You'll want to verify that against your expectations.

### CODE REVIEW

**Comment by jeffreyolchovy** [comment]
@tpolecat, I elided that last commit I used for local testing and reinserted any changes that were wiped with the revert commit (e.g. 2.12.2 to 2.12.3). If you want to re-add 2.10 support, this should be all ready to go (just rebased on your `series/0.4.x` HEAD). If not, no worries, feel free to close.

**Comment by tpolecat** [comment]
Thanks, I was off grid for a few days but I will give this a try tonight. Thanks for your work on this!

**Comment by tpolecat** [comment]
I tried this and I'm afraid it did not work. There were test failures and resolution failures, yet it continued and claimed to have pushed and released things, but nothing ever showed up on Sonatype. I appreciate your work on this but I'm done experimenting with it.

**Comment by tpolecat** [comment]
Well actually the artifacts finally showed up, but *only* for 2.10

**Comment by jeffreyolchovy** [comment]
Hmm, interesting. I can't speak to the test or resolution failures, but for the publishing process, I had to locally replace `^publishSigned` with `^publishLocal`. I don't use sbt-pgp in any of my projects, so I haven't personally vetted how it works with the cross-building scenarios. I would assume if publishSigned has been used in projects that cross-build for multiple versions of Scala, it should work here as well.

Not sure if you saw the commit I had in here before I elided it (for local testing), but it essentially replaced the releaseProcess with:
```
releaseProcess := Seq[ReleaseStep](
    releaseStepCommandAndRemaining("^clean"),
    releaseStepCommandAndRemaining("^publishLocal")
)
```
That is what I used to quickly test if this generated all of the proper artifacts (listed above).

**Comment by tpolecat** [comment]
Yeah there's some fuckery with the publishing process. No worries.

**Pull request closed without merging**
