### PR TITLE
Allow for different effects of HikariTransactor and its creation

### PR DESCRIPTION
**Pull request by sideeffffect**
/cc @piton4k
closes https://github.com/tpolecat/doobie/issues/1902

### CODE REVIEW

**Comment by jatcwang** [comment]
This is related to #1902 is that right?

**Comment by sideeffffect** [comment]
Oh yes, it is 👍
/cc @lgmyrek

**Comment by sideeffffect** [comment]
@jatcwang :pray:

**Comment by jatcwang** [comment]
I want to test the use case to get a better understanding. 
A nitpick for now is that `Resource[M, HikariTransactor[N]]` is ideally `Resource[N, HikariTransactor[M]]` as most people are used to seeing `Transactor[M]`.

**Comment by satorg** [comment]
May I add my two cents on this please. I wonder if it was better to create a separate set of functions with two effects instead of introducing breaking changes to the existing ones. Then the existing function could be kept compatible but their implementation could be changed to call the new more generic functions. The reasoning is that I guess likely 90-95% users (or so) do not need the effect separation. I believe it is a good practice in general – to provide simplified functions/methods for most common usages.

**Comment by jatcwang** [comment]
Yes I agree that'd be great @satorg :)

**Comment by sideeffffect** [comment]
> most people are used to seeing `Transactor[M]`

Good idea! I've renamed the other type variable to `M0`.

> provide simplified functions/methods for most common usages

It's not worth it. You can always just write
```scala
HikariTransactor.fromHikariConfig[IO, IO](hikariConfig)
```
instead of `fromHikariConfig[IO]`. It's a trivial change (that you typically need to make just once in your app). Duplicating all the functions just isn't worth the small benefit this would bring.

**Comment by satorg** [comment]
> It's a trivial change (that you typically need to make just once in your app). Duplicating all the functions just isn't worth the small benefit this would bring.

I totally agree that it is not that big deal. However, on the flip side changing existing functions
a. introduces a breaking change urging everyone to take an action upon the next upgrade;
b. introduces the new syntax which the majority of users do not care about.

Needless to say that adding a couple of new functions to the library is not a big deal either. No code duplication necessary there – more common used functions can simply call to more generic but relatively rare used ones. In other words: either do it just once in the library and that's it _versus_ everyone does just once but in each project that uses the library.

That said, I realize that it is absolutely matter of perception which of the two sides outweighs.

**Comment by sideeffffect** [comment]
> No code duplication necessary there

Unfortunately it is a lot of code duplication. Majority of the code would be the long function signatures (which you can't reuse in contrast to function bodies). We're in an RC phase, we can afford changes like these.

Of course, if we were stable already, I'd go with the worse, but compatible, way of duplicating the code.

**Comment by jatcwang** [comment]
I'm in general agreement with @satorg here. It's best to uphold backwards compatibility and user-friendliness unless our hands are forced. 

But I can do the suggested change in a follow-up PR, no problem.

**Pull request merged**
