### PR TITLE
Fix doc

### PR DESCRIPTION
**Pull request by n4to4**

### CODE REVIEW

**Comment by tpolecat** [comment]
Brilliant, thank you!

**Comment by n4to4** [comment]
Oops, rebased (again)

**Comment by tpolecat** [comment]
I see you pronounce "SQL" as "s-q-l" and not "sequel" like I do ;-)

**Comment by n4to4** [comment]
Oh, I've never thought of that. I will revert that changes if you prefer. (there is one occurrence which says "an SQL" in 08-Fragments.md, though)

And one thing I forgot to metion. There's one more occurrence here:

```
yax/docs/src/main/tut/07-Updating.md
162:[...], which is the type of a `sql"..."` expression, represents[...]
```

I wasn't sure if it is pronounced as in normal English or it is just a symbol or something.

**Comment by tpolecat** [comment]
I think "S-Q-L" is probably more common. I'm ok with your changes.

**Comment by n4to4** [comment]
Should I change `a sql"..."` to `an sql"..."` or just leave it?

**Comment by tpolecat** [comment]
Let's go with "an sql" everywhere.

**Comment by n4to4** [comment]
Done

**Comment by tpolecat** [comment]
Thanks!

**Pull request merged**
