### PR TITLE
Composite instances for HList and HNil

### PR DESCRIPTION
**Pull request by wedens**
small step towards #99 :) This will make possible to derive Composite for HList

### CODE REVIEW

**Comment by wedens** [comment]
also closes #75 even without shapeless 2.1.0

**Comment by tpolecat** [comment]
Oh cool, I'll check it out tonight.

**Comment by tpolecat** [comment]
Hm I can't get this to work. What do I need to do?

```scala
scala> Composite[(Int,Int)]
res12: doobie.util.composite.Composite[(Int, Int)] = doobie.util.composite$LowerPriorityComposite$$anon$4$$anon$5@5a1166b2

scala> Composite[Int :: Int :: HNil]
<console>:17: error: Could not find or construct Composite[shapeless.::[Int,shapeless.::[Int,shapeless.HNil]]].
              Composite[Int :: Int :: HNil]
                       ^
```

**Comment by wedens** [comment]
Some conflict in implicit resolution. HList Composite should be higher priority (it's really weird as I have almost the sami hierarchy in my playground and it resolves without any ambiguity)

**Comment by tpolecat** [comment]
I'll look at it again when I'm more rested but I think we're good. :+1:  Thanks!

**Pull request merged**
