### PR TITLE
Refined support for doobie

### PR DESCRIPTION
**Pull request by beefyhalo**
This is my first ever open source contribution! Yaaay!

Note: Was hoping to use a doobie `InvariantViolation` instead of a plain `Exception` but the former is a sealed class. Opinions?

### CODE REVIEW

**Comment by tpolecat** [comment]
Hi Kevin, thanks! Could you please do the following:

- Add a compilation test to the `refined` project demonstrating that the defined instances are available as expected.
- Add an example usage to the `example` project.

Let me know if you need help with either. I can update the doobie book once this is merged.

rob

**Comment by fthomas** [comment]
This looks good from the refined side. :+1: Thanks, Kevin!

**Comment by tpolecat** [comment]
@beefyhalo hey any progress or comments on the requests above?

**Comment by beefyhalo** [comment]
Sorry, I haven't had a chance to put something together yet, I'll try to find some time tonight. It shouldn't take too long to come up with an example and a few tests. I'll probably ask for some feedback on the gitter channel before committing.

**Comment by tpolecat** [comment]
No worries and no rush, just checking in.

**Comment by beefyhalo** [comment]
I've been naughty... Still count on finishing this PR shortly

**Comment by beefyhalo** [comment]
Will need some help finishing this PR. Thanks @tpolecat :)

**Comment by tpolecat** [comment]
Closing this for now; will re-open against 0.3.x when I have time to work on it.

**Pull request closed without merging**
