### PR TITLE
Add Config case class

### PR DESCRIPTION
**Pull request by sideeffffect**
Adds
 * a configuration case class that is suitable for PureConfig
  * helper method `Config.makeHikariConfig` for creating a `com.zaxxer.hikari.HikariConfig`
  * helper method `HikariTransactor.fromConfig` for creating a `doobie.hikari.HikariTransactor`

(credit goes to @jakubjanecek, the original author of [`scala-server-toolkit`](https://github.com/avast/scala-server-toolkit/) where this approach is used extensively)

### CODE REVIEW

**Comment by sideeffffect** [comment]
Hi @tpolecat ! Do you think you would find time to have a look at this PR anytime soon? :pray:

**Comment by sideeffffect** [comment]
gentle ping @tpolecat :slightly_smiling_face:

**Comment by sideeffffect** [comment]
Hi @tpolecat
Is there a change that I could make or an argument I could present that would have you reconsider having something like what this PR proposes in doobie?

**Comment by jatcwang** [comment]
Hi @sideeffffect sorry for missing this PR. Rob's just [cleaning up](https://twitter.com/tpolecat/status/1432429527024771078) and closing some old PRs (Some of which I'll rerevisit and open). 
I'm fine with this addition (will comment on PR later). Meanwhile can you reset the target to `main` branch (It's CE3)?

**Comment by sideeffffect** [comment]
@jatcwang 
> reset the target to `main` branch

Do you mean to open a new PR that targets `main`? I don't know how to re-target a PR. Maybe I can't do it because it's already closed? :shrug:

**Comment by jatcwang** [comment]
@sideeffffect bit of a catch-22 here I guess :sweat_smile:  I cannot reopen as `master` branch no longer exists.
So yes, please raise a new PR for me.

**Comment by tpolecat** [comment]
Huh, sorry, I thought you could retarget. So yeah rebase on `main` and try again.

**Pull request closed without merging**
