### PR TITLE
bump scala and library versions

### PR DESCRIPTION
**Pull request by dvic**
Not sure what the policy is regarding dependency versions, but let's see if tests pass with the latest versions.

### CODE REVIEW

**Comment by tpolecat** [comment]
Thanks, fingers crossed.

**Comment by dvic** [comment]
trying with JDBC reverted to 42.0.0, seems like a JDBC type with id '2014' is causing problems. JDBC/database version mismatch?

**Comment by tpolecat** [comment]
Yeah it looks like they added a new one. I need to change the way that's handled. JDBC specifies it as an enumeration but people keep adding new values outside the spec.

**Comment by dvic** [comment]
Looks like 2014 is a missing JDBC type in the library (`TimestampWithTimezone`, introduced in JDK 8)

**Comment by tpolecat** [comment]
Ah cool. Thanks.

**Comment by dvic** [comment]
Fixes #523

**Comment by tpolecat** [comment]
Looks good. Can you add your name and a summary of these changes to `CHANGELOG.md`?

**Comment by dvic** [comment]
Done.

**Comment by tpolecat** [comment]
Thanks!

**Pull request merged**
