### PR TITLE
separate postgis via provided

### PR DESCRIPTION
**Pull request by KadekM**
Addresses #357 by separating postgis stuff into new object.

### CODE REVIEW

**Comment by tpolecat** [comment]
This seems like a much lighter approach than #358 so I'm inclined to take this route. What do you think?

**Comment by KadekM** [comment]
I'm all for simpler (this) solution. We can always split it later if needed...
I'll update doobie book in next days... Is there anything in-code I can change to make it more intuitive/better for end users?

**Comment by tpolecat** [comment]
This looks great. Let's get the doc updated and we're good. I'm going to close #358 in favor of this one.

**Comment by KadekM** [comment]
@tpolecat I had added little bit to book of doobie... do you think it's sufficient?

**Comment by gwils** [comment]
Looks good to me.

**Comment by tpolecat** [comment]
This is blocked on #362 but otherwise ready to go.

**Comment by tpolecat** [comment]
Ok I think we're good to go here. Can you rebase?

**Comment by KadekM** [comment]
Rebased.

**Comment by tpolecat** [comment]
Brilliant! Thanks for all your work on this.

**Pull request merged**
