### PR TITLE
`ap` on `Read` should combine in appropriate order

### PR DESCRIPTION
**Pull request by stephenjudkins**
Fixes https://github.com/tpolecat/doobie/issues/1256

### CODE REVIEW

**Comment by tpolecat** [comment]
tagged v0.9.3 … should be available shortly

**Comment by stephenjudkins** [comment]
@tpolecat do you think we could squeeze https://github.com/tpolecat/doobie/pull/1310 into a release as well?

**Comment by tpolecat** [comment]
hell. yeah hang on

**Comment by tpolecat** [comment]
v0.9.4

**Comment by stephenjudkins** [comment]
🙌

**Pull request merged**
