### PR TITLE
add syntax to transact over an EitherT or OptionT of ConnectionIO

### PR DESCRIPTION
**Pull request by julien-truffaut**

### CODE REVIEW

**Comment by tpolecat** [comment]
Can you rebase this on the 0.7.x branch? The build is fixed over there. Something changed with the ruby crap required for microsite generation.

**Comment by julien-truffaut** [comment]
@tpolecat I rebased on top of 0.7.x but I can't retrigger the build.

**Comment by tpolecat** [comment]
I closed and re-opened and it looks like it's building now. Thanks!

**Comment by julien-truffaut** [comment]
Why is there an ambiguous implicit for scala 2.11 and 2.12 but not for 2.13?
```
[error] /home/travis/build/tpolecat/doobie/modules/core/src/main/scala/doobie/syntax/connectionio.scala:20:33: ambiguous implicit values:
[error]  both value AsyncConnectionIO in object connection of type => cats.effect.Async[doobie.free.connection.ConnectionIO]
[error]  and method catsFreeMonadForFree in class FreeInstances of type [S[_]]=> cats.Monad[[β$18$]cats.free.Free[S,β$18$]]
[error]  match expected type cats.Monad[doobie.free.connection.ConnectionIO]
[error]       xa.transB.apply(ma.orElseF(HC.rollback.map(_ => None)).value)
```

**Comment by julien-truffaut** [comment]
@tpolecat build pass

**Comment by julien-truffaut** [comment]
any change you want me to make? I can update my branch otherwise

**Comment by julien-truffaut** [comment]
@tpolecat thanks for updating my branch :)

**Pull request merged**
