### PR TITLE
Added set and setOpt combinators

### PR DESCRIPTION
**Pull request by coltfred**
- Added fragments combinators for set.

### CODE REVIEW

**Comment by tpolecat** [comment]
👍 can you add your name and a bullet point to the "Notable Work in Progress for Version 0.4.2" section of `CHANGELOG.md`?

**Comment by coltfred** [comment]
Sure thing. I'll do that first thing in the morning.

**Comment by tpolecat** [comment]
You'll also need to rebase.

**Comment by coltfred** [comment]
@tpolecat Done.

**Pull request merged**
