### PR TITLE
Composite instance for Generic

### PR DESCRIPTION
**Pull request by wedens**
`Composite` for any type isomorphic to `HList`. more general (and preferred) version of `ProductTypeClass` instance

### CODE REVIEW

**Comment by tpolecat** [comment]
This looks great, thanks! I will give it a closer look later today.

**Comment by tpolecat** [comment]
Not sure what's going on here, but this works fine on `master`.

```scala
scala> case class Foo(n: Int, b: String :: String :: HNil, c: Option[Double])
defined class Foo

scala> Composite[Foo]
res9: doobie.util.composite.Composite[Foo] = doobie.util.composite$LowerPriorityComposite$$anon$6@44fd0e0d

scala> Composite[Foo :: HNil]
java.lang.StackOverflowError
  at doobie.util.composite$LowerPriorityComposite$class.genericComposite(composite.scala:86)
  at doobie.util.composite$Composite$.genericComposite(composite.scala:43)
  at fresh$macro$99$1.value$lzycompute(<console>:16)
  at fresh$macro$99$1.value(<console>:16)
  at fresh$macro$99$1.value(<console>:16)
  at doobie.util.composite$LowerPriorityComposite$$anon$6.<init>(composite.scala:90)
  ...
```

**Comment by wedens** [comment]
hm. I can't reproduce this problem. is it always throws SOE?

**Comment by tpolecat** [comment]
Yes, always happens.

```
doobie (wedens-generic-composite)$ java -version
java version "1.7.0_67"
Java(TM) SE Runtime Environment (build 1.7.0_67-b01)
Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)
doobie (wedens-generic-composite)$ sbt core/console
[info] Loading project definition from /Users/rnorris/Scala/doobie/project
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[info] Set current project to doobie (in build file:/Users/rnorris/Scala/doobie/)
[info] Compiling 1 Scala source to /Users/rnorris/Scala/doobie/core/target/scala-2.11/classes...
[info] Starting scala interpreter...
[info] 
Welcome to Scala version 2.11.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_67).
Type in expressions to have them evaluated.
Type :help for more information.

scala> import doobie.imports._, shapeless._
import doobie.imports._
import shapeless._

scala> case class Foo(n: Int, b: String :: String :: HNil, c: Option[Double])
defined class Foo

scala> Composite[Foo]
res0: doobie.util.composite.Composite[Foo] = doobie.util.composite$LowerPriorityComposite$$anon$6@73eb8e7f

scala> Composite[Foo :: HNil]
java.lang.StackOverflowError
  at fresh$macro$22$1.value(<console>:16)
  at fresh$macro$22$1.value(<console>:16)
  at doobie.util.composite$LowerPriorityComposite$$anon$6.<init>(composite.scala:90)
  ...
```

**Comment by wedens** [comment]
It's reproducible on other computer

**Comment by tpolecat** [comment]
Looks good! :+1:

**Pull request merged**
