### PR TITLE
doc updates

### PR DESCRIPTION
**Pull request by dvic**
focuses on #474 #477 #506

### CODE REVIEW

**Comment by dvic** [comment]
Updates now also contribute to #482.

Not sure how useful this PR is but hopefully it helps you getting the docs up-to-date with the latest 0.4.x. Feel free to pick bits and pieces if you need to and feedback is most welcome 😄 !

A few questions:
* how can I generate the HTML for the docs locally? I was looking for the SBT command but I could not find it
* how are the published doobie books versioned? do they get published every time a doobie release is made? maybe it's a good idea to also publish the books for the SNAPSHOT version?

**Comment by dvic** [comment]
rebased on `series/0.4.x`

**Comment by tpolecat** [comment]
@dvic thanks for all of this. Right now it's a pain to create the doc locally. It relies on having my personal website checked out and having Jekyll set up. One of the first things I want to do for 0.5.0 is move to sbt-microsites, which will simplify all this and allow auto-updating.

**Comment by tpolecat** [comment]
Great stuff, thanks for your work on this!

**Pull request merged**
