### PR TITLE
add adopters

### PR DESCRIPTION
**Pull request by KadekM**

### CODE REVIEW

**Comment by brianpendleton** [comment]
👍 , we're using in the `fintech` group at Circle.  Managing FX pricing feeds and market data aggregation.  I plan to roll it out as I replace more of our stack with Scala

**Comment by tpolecat** [comment]
I have mixed feelings about this kind of thing … I like the code to speak for itself. But as you point out it's a common practice and can help people worry less. I'm going to think about it.

**Comment by mdmoss** [comment]
I think this could be a good thing. Knowing other businesses are users might make it more attractive to adopt, especially when people who are less technical involved in making the decision. It would have smoothed the way for my team a little in the beginning.

**Comment by KadekM** [comment]
I'm with @mdmoss , very often, if not always, one of first questions raised is "who uses it", at least from my experience.

**Comment by tpolecat** [comment]
Yeah, I know they're using it at some big impressive-sounding companies but I'm not confident that they would want their names used. So if it's a list of companies nobody has heard of it could have a negative net effect. Dunno. Thanks for the input though, I'm on the fence.

**Comment by KadekM** [comment]
Sounds reasonable. I didnt think of possible negative net effect, but yea,
then it may be better not include it at least for now.

**Pull request closed without merging**
