### PR TITLE
Add Adopters list to documentation

### PR DESCRIPTION
**Pull request by jozic**
The idea is to create the list of Adopters that use `doobie` in production, similar to what [Cats has in README](https://github.com/typelevel/cats/blob/master/README.md#adopters).
The motivation is to promote the library and make people feel more confident.
Thanks everyone!

### CODE REVIEW

**Comment by jozic** [comment]
@tpolecat this is not the longest list of adopters, but I managed to put their at least my company :)

**Comment by jatcwang** [comment]
Thanks @jozic good idea. Seems like CI is complaining about the broken link to `./index.md`. I think using the full URL should work?

**Comment by jozic** [comment]
@jatcwang fixed the link!
Thanks for checking it

**Comment by jatcwang** [comment]
Hi @jozic can you do me a favour and add a few more companies? I'll post this on twitter.

Let's start with mine: medidata.com

**Comment by stephenjudkins** [comment]
`- [HIFI] (https://hi.fi)`

**Comment by skennedy** [comment]
Big fans of doobie @ lenses.io 👍

**Comment by zmccoy** [comment]
` - [Banno at Jack Henry & Associates] (https://banno.com/)`

**Comment by jozic** [comment]
@jatcwang 
added all the suggested so far companies

**Comment by axuan25** [comment]
www.reachfive.com :)

**Comment by fanf** [comment]
`- [Rudder](https://rudder.io)`

**Comment by adamw** [comment]
`- [SoftwareMill](https://softwaremill.com)`

**Comment by dragisak** [comment]
- [Crunchbase](https://crunchbase.com)

**Comment by tpolecat** [comment]
```
- [NORLab](https://noirlab.edu)
```

**Comment by jozic** [comment]
Updated!

**Comment by TimWSpence** [comment]
You can add [ITV](https://www.itv.com/) as well :)

**Comment by Ssstlis** [comment]
`- [RaiffeisenBank Russia](https://raiffeisen.ru)`

**Comment by hmemcpy** [comment]
`- [Unit](https://unit.co)`

Hopefully soon will become Skunk early adopters as well :)

**Comment by guersam** [comment]
`- [Doomoolmori](https://doomoolmori.com)`

**Comment by jozic** [comment]
Updated!

**Comment by jatcwang** [comment]
Thank you @jozic. Better merge this before more people show up :smile:

**Pull request merged**
